server:
    port: 8080
    context-path: /
    
log:
    path: E:\资料\File\工作记录\logging
    level: info

spring:
    session:
        store-type: none  
    datasource:
        url: jdbc:sqlserver://172.16.86.100:1433;databaseName=gspD
        username: gspadmin
        password: gspadmin01
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#        url: jdbc:mysql://172.16.88.112:8066/FFLOG?useUnicode=true&amp;characterEncoding=UTF-8
#        username: root
#        password: root
#       # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
        database: 0
        host: 172.16.88.114
        port: 6379
        password: 111111
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
        timeout: 0   
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request

#以下属性不可用
#mybatis:
#    pagehelper:
#        dialect: mysql
#        reasonable: true
#        supportMethodsArguments: true
#        returnPageInfo: check
#        params: count=countSql
#    mapper:
#        mappers: tk.mybatis.springboot.util.MyMapper
#        notEmpty: true
#        style: camelhump
#    sqlSessionFactoryBean:
#        mapperLocations:
#            - classpath:mapper/*.xml
#            - classpath:mapper2/*.xml
#        typeAliasesPackage: tk.mybatis.springboot.model
#    mapperScanner:
#        basePackage: tk.mybatis.springboot.mapper
